### PR TITLE
Fix/radius ux

### LINKED ISSUE #129: UX tidy up for radius filter
- [x] Change radius label to "Distance (km)"
- [x] If you picked a region can you make the radius/distance non-applicable
- [x] Add padding to the radio buttons, making the buttons easier to select.

### PR DESCRIPTION
**Pull request by JacOng17**
Added padding for radius. Changed name:radius to name:distance. 

Distance filter only appears when location selected.

Closes #129 

distance

### CODE REVIEW

**Comment by Br3nda** [comment]
@JacOng17 can you fix the small css lint issues on codeclimate before merging

**Comment by JacOng17** [comment]
@Br3nda Done! :smile:  Commit ref: 0d3b763

File: src/components/search-form.js [hunk 1]
```diff
@@ -51,17 +51,18 @@ export default class SearchForm extends Component {
...
-                  <label>
-                    <Field name="radius" component="input" type="radio" value={radius} />
-                    {radius}
-                  </label>
-                );
-              })}
-            </div>
+            {region ? (
+              <div className="radio-group">
+                <p>Distance (Km):</p>
```
Comment (mischa-s) [inline src/components/search-form.js]: Nice work, why is this no longer in a label tag?
